const API_URL='https://kgbbnyypzteqimexnpfp.supabase.co'
const API_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnYmJueXlwenRlcWltZXhucGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDEzNzExMjksImV4cCI6MjAxNjk0NzEyOX0.NSZOicMVGNGkaH8nJll8P8ar0BWvB1vusth5pBaeim0'

export { API_URL, API_KEY}